apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-listing-deployment
  labels:
    app: server-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-api
  template:
    metadata:
      labels:
        app: server-api
    spec:
      containers:
      - name: server-api
        image: amila15/car-listing-marketplace:v1.0.0 
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 3000
