apiVersion: v1
kind: Service
metadata:
  labels:
    app: server-api
  name: car-listing-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: server-api
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    planetscale.com/cluster: car-listing-marketplace
    planetscale.com/component: vtgate
  name: database-api
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    planetscale.com/cluster: car-listing-marketplace
    planetscale.com/component: vtgate
