apiVersion: v1
kind: Service
metadata:
  labels:
    app: server-api
  name: car-listing-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: server-api
status:
  loadBalancer: {}
