apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: car-listing-marketplace
spec:
  images:
    vtctld: vitess/lite@sha256:925c00a2dad52fdd4ab828523b5ae2d119e6116f5c3b75a0e1649373f6cbf6ba
    vtadmin: vitess/vtadmin@sha256:c638f31892af685e99a2ca99a3c089feeb6dabe5a01a734f6886c8c45c83eb3a
    vtgate: vitess/lite@sha256:925c00a2dad52fdd4ab828523b5ae2d119e6116f5c3b75a0e1649373f6cbf6ba
    vttablet: vitess/lite@sha256:925c00a2dad52fdd4ab828523b5ae2d119e6116f5c3b75a0e1649373f6cbf6ba
    vtbackup: vitess/lite@sha256:925c00a2dad52fdd4ab828523b5ae2d119e6116f5c3b75a0e1649373f6cbf6ba
    vtorc: vitess/lite@sha256:925c00a2dad52fdd4ab828523b5ae2d119e6116f5c3b75a0e1649373f6cbf6ba
    mysqld:
      mysql80Compatible: vitess/lite@sha256:925c00a2dad52fdd4ab828523b5ae2d119e6116f5c3b75a0e1649373f6cbf6ba
    mysqldExporter: prom/mysqld-exporter@sha256:9f4fb61cca309cb4a8c1b9ed9fb4aa75af0f7a21f36d3954667db37c062a0172
  cells:
  - name: zone1
    gateway:
      authentication:
        static:
          secret:
            name: car-listing-marketplace-cluster-config
            key: users.json
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 256Mi
  vitessDashboard:
    cells:
    - zone1
    extraFlags:
      security_policy: read-only
    replicas: 1
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  vtadmin:
    rbac:
      name: car-listing-marketplace-cluster-config
      key: rbac.yaml
    cells:
      - zone1
    apiAddresses:
      - http://localhost:14001
    replicas: 1
    readOnly: false
    apiResources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    webResources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  keyspaces:
  - name: car-listing-marketplace
    durabilityPolicy: none
    turndownPolicy: Immediate
    vitessOrchestrator:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      extraFlags:
        recovery-period-block-duration: 5s
    partitionings:
    - equal:
        parts: 1
        shardTemplate:
          databaseInitScriptSecret:
            name: car-listing-marketplace-cluster-config
            key: init_db.sql
          tabletPools:
          - cell: zone1
            type: replica
            replicas: 2
            vttablet:
              extraFlags:
                db_charset: utf8mb4
              resources:
                limits:
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
            mysqld:
              resources:
                limits:
                  memory: 1024Mi
                requests:
                  cpu: 100m
                  memory: 512Mi
            dataVolumeClaimTemplate:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
    - equal:
        parts: 2
        shardTemplate:
          databaseInitScriptSecret:
            name: car-listing-marketplace-cluster-config
            key: init_db.sql
          tabletPools:
          - cell: zone1
            type: replica
            replicas: 1
            vttablet:
              extraFlags:
                db_charset: utf8mb4
              resources:
                limits:
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
            mysqld:
              resources:
                limits:
                  memory: 1024Mi
                requests:
                  cpu: 100m
                  memory: 512Mi
            dataVolumeClaimTemplate:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
  updateStrategy:
    type: Immediate
